
package com.example.lxk.demolxk.lxk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 就诊挂号信息，返回值说明：0-安全验证失败；1-操作成功；2-非规范的数据项；3-异常;
     * 
     * @param strJzgh
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "saveData_jzgh", action = "http://tempuri.org/saveData_jzgh")
    @WebResult(name = "saveData_jzghResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "saveData_jzgh", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataJzgh")
    @ResponseWrapper(localName = "saveData_jzghResponse", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataJzghResponse")
    public String saveDataJzgh(
        @WebParam(name = "strJzgh", targetNamespace = "http://tempuri.org/")
        String strJzgh);

    /**
     * 急诊信息，返回值说明：0-安全验证失败；1-操作成功；2-非规范的数据项；3-异常;
     * 
     * @param strJz
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "saveData_jz", action = "http://tempuri.org/saveData_jz")
    @WebResult(name = "saveData_jzResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "saveData_jz", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataJz")
    @ResponseWrapper(localName = "saveData_jzResponse", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataJzResponse")
    public String saveDataJz(
        @WebParam(name = "strJz", targetNamespace = "http://tempuri.org/")
        String strJz);

    /**
     * 毒麻药品，返回值说明：0-安全验证失败；1-操作成功；2-非规范的数据项；3-异常;
     * 
     * @param strDmyp
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "saveData_Dmyp", action = "http://tempuri.org/saveData_Dmyp")
    @WebResult(name = "saveData_DmypResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "saveData_Dmyp", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataDmyp")
    @ResponseWrapper(localName = "saveData_DmypResponse", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataDmypResponse")
    public String saveDataDmyp(
        @WebParam(name = "strDmyp", targetNamespace = "http://tempuri.org/")
        String strDmyp);

    /**
     * 住院信息，返回值说明：0-安全验证失败；1-操作成功；2-非规范的数据项；3-异常;
     * 
     * @param strZy
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "saveData_zy", action = "http://tempuri.org/saveData_zy")
    @WebResult(name = "saveData_zyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "saveData_zy", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataZy")
    @ResponseWrapper(localName = "saveData_zyResponse", targetNamespace = "http://tempuri.org/", className = "com.example.lxk.demolxk.lxk.SaveDataZyResponse")
    public String saveDataZy(
        @WebParam(name = "strZy", targetNamespace = "http://tempuri.org/")
        String strZy);

}
