eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      preferIpAddress: true
server:
  port: 8763
spring:
  application:
    name: service-hi